version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: pipenv run python3 api/app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - db
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      # Flask variables
      - FLASK_APP=api/app.py
      - FLASK_DEBUG=${FLASK_DEBUG}
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_RUN_HOST=${FLASK_RUN_HOST}
      - FLASK_RUN_PORT=${FLASK_RUN_PORT}
      # Database variables
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}

  db:
    image: mongo:latest
    hostname: db_mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
